# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-29 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20180729_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernames',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
