# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-28 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180728_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='duration',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
