# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-28 10:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180728_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(20, 36000)),
        ),
        migrations.AddField(
            model_name='product',
            name='max_duration',
            field=models.IntegerField(default=0),
        ),
    ]
