# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-28 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcondition',
            name='purchase_date',
            field=models.DateTimeField(default=False),
        ),
    ]
