# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-28 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20180729_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('GA', 'Gardening'), ('CO', 'Construction'), ('MA', 'Maintenacne'), ('TA', 'Travel')], max_length=2),
        ),
    ]
