# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-29 03:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20180729_0833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='duration',
        ),
    ]
